version: '2'

services:

  fluentd:
    image: fluent/fluentd:edge
    mem_limit: "512m"
    ports:
      - "5170:5170"
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/tmp/logs
