# escape=\
FROM grafana/grafana:latest

MAINTAINER Konrad Otrębski

COPY ./provisioning /etc/grafana/provisioning
COPY ./dashboards /var/lib/grafana/dashboards
COPY ./grafana.ini /etc/grafana/grafana.ini
